export const siteConfig = {
  name: "AI Career Guide",
  shortName: "AI Career Guide",
  description:
    "Build stronger CVs, improve ATS match rates, use an AI career assistant, find jobs, generate cover letters, prepare for interviews, and manage your search in one workspace.",
  url: "https://aicareerguide.uk",
  ogImage: "/opengraph-image?v=20260414",
  searchLogo: "/app-install-icon-512.png",
  supportEmail: "info@aicareerguide.uk",
  xHandle: "@aicareerguide",
};

export const defaultKeywords = [
  "AI CV builder",
  "AI resume builder",
  "free CV builder",
  "free CV editor",
  "free resume builder",
  "CV builder",
  "online CV builder",
  "professional CV builder",
  "resume builder",
  "free ATS checker",
  "free ATS CV checker",
  "ATS resume checker",
  "ATS CV checker",
  "CV checker",
  "resume checker",
  "CV templates",
  "career coach",
  "AI career assistant",
  "AI career mentor",
  "cover letter generator",
  "AI cover letter generator",
  "interview prep",
  "AI interview prep",
  "mock interview practice",
  "job application tracker",
  "job tracker",
  "job search tracker",
  "free job search",
  "UK job search",
  "live job search",
  "job search tool",
  "resume templates",
  "job search dashboard",
  "career SaaS",
  "AI Career Guide",
];

export const publicSiteRoutes = [
  "/",
  "/cv-builder",
  "/free-cv-builder",
  "/ats-cv-checker",
  "/cv-templates",
  "/cv-examples",
  "/uk-cv-format",
  "/graduate-cv-template",
  "/cover-letter-examples",
  "/cv-personal-statement-examples",
  "/career-change-cv",
  "/nhs-cv-template",
  "/finance-cv-template",
  "/tech-cv-template",
  "/compare",
  "/compare/zety-alternative",
  "/compare/resume-io-alternative",
  "/compare/rezi-alternative",
  "/compare/kickresume-alternative",
  "/compare/novoresume-alternative",
  "/compare/enhancv-alternative",
  "/ai-career-assistant",
  "/job-search",
  "/ai-interview-prep",
  "/cover-letter-generator",
  "/pricing",
  "/support",
  "/privacy",
  "/terms",
];
