import Link from "next/link";
import { ArrowRight, Check, ChevronRight, Sparkles } from "lucide-react";
import { PublicHeader } from "@/components/marketing/public-header";
import { SiteFooter } from "@/components/marketing/site-footer";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { marketingHeaderItems } from "@/lib/marketing-nav";
import { PLANS } from "@/lib/plans";
import { createMetadata } from "@/lib/metadata";

export const metadata = createMetadata({title:"AI CV Builder for UK Job Seekers | AI Career Guide",description:"Build a stronger UK CV, check it against job descriptions and apply with confidence. Start free or upload your existing CV.",path:"/",keywords:["AI CV builder UK","free CV builder UK","ATS CV checker","CV templates"]});
const faq=[["Can I use my existing CV?","Yes. Upload your current CV and continue in the editor without starting again."],["Is there a free plan?","Yes. The Free plan includes one CV, three ATS scans, five AI generations and five ATS-safe templates."],["Will the templates work with ATS software?","The templates use clear structure and restrained layouts designed to remain readable by applicant tracking systems."],["Do I need to be good at writing?","No. The guided builder helps turn responsibilities into specific evidence while keeping you in control of the final wording."]];

export default function Home(){const structuredData={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))};return <div className="career-home min-h-screen"><PublicHeader items={marketingHeaderItems}/><main id="main-content">
  <section className="career-hero"><div className="career-orb career-orb-a"/><div className="career-orb career-orb-b"/><div className="career-grid"/><div className="marketing-shell relative z-10 grid gap-10 pb-16 pt-14 lg:grid-cols-[.72fr_1.28fr] lg:items-center lg:pb-24 lg:pt-20">
    <div className="hero-copy"><p className="career-kicker"><span/>Your career intelligence workspace</p><h1>Build a stronger CV. <em>Match more jobs.</em> Apply with confidence.</h1><p className="hero-lede">Turn your experience into clear evidence, tailor it to the role and keep every application moving in one intelligent workspace.</p><div className="hero-actions"><Link className="career-primary" href="/signup?intent=create-cv">Build My CV Free <ArrowRight/></Link><Link className="career-secondary" href="/signup?intent=upload-cv">Upload My CV</Link></div><p className="hero-trust"><Check/> Free plan available <span/> No card required</p>
    </div><CareerCanvas/>
  </div></section>
  <Workflow/>
  <section id="product" className="studio-chapter"><div className="marketing-shell"><div className="chapter-intro"><p className="career-kicker"><span/>01 · CV Studio</p><h2>Your experience, transformed into evidence.</h2><p>Write inside a focused document studio. Dan spots vague language, offers a stronger version and keeps every edit yours to approve.</p></div><div className="studio-scene"><div className="studio-toolbar"><span className="studio-dots">● ● ●</span><span>CV Studio / Operations Manager</span><span>Saved just now</span></div><div className="studio-layout"><div className="studio-rail"><b>Structure</b>{["Profile","Experience","Education","Skills"].map((x,i)=><span className={i===1?"active":""} key={x}>{i===1?"◈":"○"} {x}</span>)}</div><CVPaper/><div className="rewrite-panel"><p className="panel-label">DAN · AI REWRITE</p><strong>Make this achievement specific</strong><div className="rewrite-before"><small>ORIGINAL</small><s>Responsible for improving team processes.</s></div><div className="rewrite-after"><small>SUGGESTED</small><p>Redesigned weekly planning across a 12-person team, cutting overdue work by 28%.</p></div><div className="rewrite-actions"><button>Dismiss</button><button>Apply rewrite</button></div></div></div></div></div></section>
  <section className="ats-chapter"><div className="ats-stars"/><div className="marketing-shell relative z-10 grid gap-12 lg:grid-cols-[.65fr_1.35fr] lg:items-center"><div><p className="career-kicker dark"><span/>02 · ATS Diagnostic</p><h2>See the signal recruiters’ systems see.</h2><p className="chapter-copy-dark">Compare your CV against the role, understand keyword coverage and leave with a precise action queue—not a mystery score.</p><Link className="text-link-dark" href="/signup?intent=ats-check">Run an ATS check <ArrowRight/></Link></div><div className="diagnostic-console"><div className="score-module"><div className="score-ring"><div><strong>82</strong><span>Strong match</span></div></div><p>Role alignment</p><small>7 actions remain</small></div><div className="keyword-module"><div className="console-heading"><span>KEYWORD COVERAGE</span><b>14 / 18</b></div>{[["Stakeholder management",92],["Forecasting",86],["Process improvement",78],["Budget ownership",38]].map(([x,n])=><div className="keyword-row" key={x}><div><span>{x}</span><small>{n}%</small></div><i><b style={{width:`${n}%`}}/></i></div>)}</div><div className="action-module"><span>PRIORITY ACTION</span><strong>Add budget ownership evidence</strong><p>The job description mentions this twice. Add a truthful example if you have one.</p><button>Open in editor <ChevronRight/></button></div></div></div></section>
  <CommandCentre/>
  <Templates/>
  <Pricing/>
  <section className="faq-chapter"><div className="marketing-shell grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="career-kicker"><span/>Before you begin</p><h2>A few useful answers.</h2></div><Accordion type="single" collapsible>{faq.map(([q,a],i)=><AccordionItem key={q} value={`${i}`}><AccordionTrigger className="text-left text-base">{q}</AccordionTrigger><AccordionContent className="text-base leading-7 text-slate-600">{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>
  <section className="final-command"><div className="marketing-shell"><div className="final-inner"><div className="command-grid"/><p>YOUR NEXT MOVE</p><h2>Turn your next application into your strongest one.</h2><span>Build for free. Keep control of every word.</span><Link href="/signup?intent=create-cv">Enter your CV Studio <ArrowRight/></Link></div></div></section>
  </main><SiteFooter/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData)}}/></div>}

function CareerCanvas(){return <div className="career-canvas" aria-label="Career workspace preview"><div className="canvas-top"><div><span className="status-dot"/>CAREER CANVAS</div><span>Operations Manager · Draft 3</span></div><div className="canvas-body"><div className="dan-float"><div className="dan-avatar">D</div><div><small>DAN · CAREER AGENT</small><strong>3 ways to sharpen this CV</strong><p>I found one vague achievement and two missing role keywords.</p></div></div><CVPaper/><div className="ats-float"><div className="mini-ring"><b>82</b></div><div><small>ATS MATCH</small><strong>Strong foundation</strong><span>14 of 18 keywords covered</span></div></div><div className="diff-float"><small>AI REWRITE · READY</small><s>Managed a busy team...</s><p>Led a 12-person team across three delivery streams...</p><button>Review change <ChevronRight/></button></div></div><div className="pipeline-strip"><span><i/>CV strengthened</span><b>→</b><span><i/>ATS checked</span><b>→</b><span className="next"><i/>Next: tailor to role</span></div></div>}
function CVPaper(){return <div className="cv-paper"><div className="cv-name">ALEX MORGAN</div><div className="cv-role">OPERATIONS MANAGER</div><div className="cv-contact">London · alex@email.com · 07•• ••• •••</div><div className="cv-section"><b>PROFILE</b><p>Operations leader with experience improving delivery systems, team performance and cross-functional planning.</p></div><div className="cv-section"><b>EXPERIENCE</b><strong>Senior Operations Manager</strong><small>Northstar Group · 2021—Present</small><p>• Redesigned weekly planning across a 12-person team, cutting overdue work by 28%.</p><p>• Built forecasting dashboards used by three department leads.</p></div><div className="cv-section muted-lines"><b>EARLIER EXPERIENCE</b><i/><i/><i/></div></div>}
function Workflow(){return <section className="workflow"><div className="marketing-shell"><p className="workflow-label">ONE CONNECTED WORKFLOW</p><div className="workflow-rail">{[["01","Build","Shape your experience"],["02","Diagnose","Find the gaps"],["03","Tailor","Match the role"],["04","Track","Move it forward"]].map(([n,t,c],i)=><div className={i===0?"active":""} key={t}><span>{n}</span><p><strong>{t}</strong><small>{c}</small></p></div>)}</div></div></section>}
function CommandCentre(){return <section className="command-chapter"><div className="marketing-shell"><div className="command-heading"><p className="career-kicker"><span/>03 · Career Command Centre</p><h2>Your job search finally has a control room.</h2><p>Keep applications, follow-ups and next actions visible—while Dan helps you focus on what matters now.</p></div><div className="command-ui"><div className="command-nav"><b>Command Centre</b><span>Overview</span><span>Applications</span><span>Documents</span><span>Interview prep</span></div><div className="command-main"><div className="command-welcome"><small>THURSDAY, 17 JULY</small><h3>Good morning, Alex.</h3><p>You have two high-priority actions today.</p></div><div className="next-actions"><span>NEXT BEST ACTION</span><b>Tailor your CV for Product Operations Lead</b><p>Deadline in 3 days · Your current ATS match is 68</p><button>Continue tailoring <ArrowRight/></button></div><div className="pipeline"><div className="pipeline-head"><b>Application pipeline</b><span>7 active</span></div>{[["SAVED","Product Ops Lead","Horizon"],["APPLIED","Operations Manager","Northstar"],["INTERVIEW","Delivery Lead","Metric"]].map(([s,r,c])=><div className="job-row" key={r}><span>{s}</span><b>{r}</b><small>{c}</small><i>•••</i></div>)}</div></div><div className="dan-side"><div className="dan-avatar large">D</div><span>DAN INTELLIGENCE</span><h3>Your week, prioritised.</h3><div className="insight"><i/>Your Horizon CV needs 3 keywords before Friday.</div><div className="insight"><i/>Prepare one STAR example for tomorrow’s interview.</div><Link href="/signup?intent=create-cv">Ask Dan anything <ArrowRight/></Link></div></div></div></section>}
const templateCovers=[
  {name:"Executive",fit:"Leadership & finance",style:"executive",badge:"Recruiter ready"},
  {name:"Modern",fit:"Product & technology",style:"modern",badge:"ATS safe"},
  {name:"Editorial",fit:"Creative & communications",style:"editorial",badge:"Recruiter ready"},
  {name:"Precision",fit:"Operations & consulting",style:"precision",badge:"ATS safe"},
];
function TemplateDocument({style}:{style:string}){return <div className={`cv-cover cv-cover-${style}`} aria-hidden="true"><div className="cv-cover-sidebar"><div className="cv-cover-monogram">AM</div><div className="cv-cover-side-block"><b>CONTACT</b><span>London, UK</span><span>alex.morgan@email.com</span><span>+44 7700 900 123</span></div><div className="cv-cover-side-block"><b>EXPERTISE</b><span>Strategy & planning</span><span>Team leadership</span><span>Process design</span><span>Commercial growth</span></div></div><div className="cv-cover-main"><header><p className="cv-cover-eyebrow">OPERATIONS LEADER</p><h3>Alex Morgan</h3><p className="cv-cover-contact">London, UK&nbsp;&nbsp;•&nbsp;&nbsp;alex.morgan@email.com&nbsp;&nbsp;•&nbsp;&nbsp;+44 7700 900 123</p></header><section><h4>Profile</h4><p>Operations leader with 8+ years building high-performing teams and scalable systems across fast-growth organisations.</p></section><section><h4>Experience</h4><div className="cv-cover-role"><div><strong>Senior Operations Manager</strong><small>Northstar Group · London</small></div><time>2021—Present</time></div><ul><li>Led a 12-person team across three delivery streams, improving on-time delivery by 28%.</li><li>Built forecasting systems adopted by three departments and the executive team.</li></ul><div className="cv-cover-role"><div><strong>Operations Lead</strong><small>Horizon Labs · London</small></div><time>2018—2021</time></div><ul><li>Redesigned customer onboarding, reducing time-to-value from 21 to 12 days.</li></ul></section><section className="cv-cover-bottom"><div><h4>Education</h4><strong>BSc Business Management</strong><small>University of Manchester</small></div><div><h4>Skills</h4><p>Forecasting · OKRs · Change management · Stakeholder leadership</p></div></section></div></div>}
function Templates(){return <section className="templates-chapter"><div className="marketing-shell"><div className="template-heading"><div><p className="career-kicker"><span/>Designed to get noticed</p><h2>Choose the CV recruiters remember.</h2></div><p>Your content stays intact while you explore a new look. Switch designs in one click—without rewriting a single section.</p></div><div className="template-runway" aria-label="CV template previews">{templateCovers.map((template)=><article className="template-card" key={template.name}><Link className="template-cover-link" href="/signup?intent=create-cv" aria-label={`Use the ${template.name} CV template`}><span className="template-badge"><Check/>{template.badge}</span><TemplateDocument style={template.style}/><span className="template-use">Use this template <ArrowRight/></span></Link><div className="template-meta"><div><h3>{template.name}</h3><p>{template.fit}</p></div><span>A4 · 2 pages</span></div></article>)}</div><Link className="template-link" href="/cv-templates">Explore all CV templates <ArrowRight/></Link></div></section>}
function Pricing(){return <section className="pricing-chapter"><div className="marketing-shell"><div className="pricing-head"><p className="career-kicker"><span/>Choose your pace</p><h2>Start free. Scale when your search does.</h2><Link href="/pricing">Compare every feature <ArrowRight/></Link></div><div className="pricing-rail">{[PLANS.free,PLANS.pro,PLANS.master].map((p,i)=><article className={i===1?"featured":""} key={p.id}>{i===1&&<span className="popular">MOST POPULAR</span>}<p>{p.name}</p><h3>{p.price}<small>{p.price!=="£0"?" / month":" forever"}</small></h3><ul>{p.features.slice(0,4).map(x=><li key={x}><Check/>{x}</li>)}</ul><Link href={`/signup?intent=select-plan&plan=${p.id}`}>{i===0?"Start free":`Choose ${p.name}`} <ArrowRight/></Link></article>)}</div><p className="agency-line"><b>Career organisation or hiring team?</b> Agency support is scoped separately. <Link href="/pricing">View Agency</Link></p></div></section>}
